// Define types for the AI-driven quoting system

// Project types
export type ProjectType = 'driveway' | 'patio' | 'road' | 'parking_lot' | 'foundation' | 'landscaping' | 'commercial' | 'residential' | 'industrial' | 'infrastructure' | 'other';

// Project sector
export type Sector = 'public' | 'private' | 'government' | 'residential' | 'commercial' | 'industrial';

// Basic project information
export interface ProjectInfo {
  name: string;
  description: string;
  type: ProjectType;
  sector: Sector;
  location: string;
  size: string;
  timeline: string;
  budget: string;
  specialRequirements: string[];
}

// Material recommendation from Claude AI
export interface MaterialRecommendation {
  id: string;
  name: string;
  description: string;
  category: string;
  quantity: number;
  unit: string;
  unitPrice: number;
  totalPrice: number;
  reasoning: string[];
  alternatives?: {
    id: string;
    name: string;
    description: string;
    priceImpact: number;
    qualityImpact: string;
    reasoning: string;
  }[];
  specifications?: {
    [key: string]: string | number;
  };
}

// Plant/supplier location
export interface Plant {
  id: string;
  name: string;
  location: string;
  distance: string;
  rating: number;
  leadTime: string;
  availableMaterials: string[];
  specialCapabilities?: string[];
  contact?: {
    phone: string;
    email: string;
  };
}

// Delivery information
export interface DeliveryInfo {
  address: {
    street: string;
    city: string;
    state: string;
    zipCode: string;
  };
  date: string;
  timeWindow?: string;
  specialInstructions?: string;
  contactName: string;
  contactPhone: string;
  contactEmail: string;
}

// Weather condition for delivery planning
export interface WeatherCondition {
  date: string;
  condition: 'sunny' | 'cloudy' | 'rainy' | 'snowy' | 'windy' | 'stormy';
  temperature: number;
  precipitationChance: number;
  impact: string;
  recommendation: string;
}

// Project insight generated by Claude AI
export interface ProjectInsight {
  category: 'material' | 'timeline' | 'budget' | 'logistics' | 'weather' | 'regulations';
  title: string;
  description: string;
  importance: 'low' | 'medium' | 'high';
  recommendation?: string;
  potentialSavings?: number;
  potentialRisks?: string[];
}

// Claude AI message
export interface AIMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
  timestamp?: Date;
  metadata?: Record<string, any>;
}

// Quote state
export interface QuoteState {
  projectInfo: ProjectInfo;
  materials: MaterialRecommendation[];
  plants: Plant[];
  selectedPlantId?: string;
  delivery: DeliveryInfo;
  weatherConditions?: WeatherCondition[];
  insights: ProjectInsight[];
  conversation: AIMessage[];
  totalCost: number;
  quoteNumber?: string;
  estimatedCompletion?: string;
  status: 'draft' | 'submitted' | 'approved' | 'rejected';
  createdAt: Date;
  updatedAt: Date;
}
